name: yttrium_music
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  lucide_icons_flutter: ^3.1.8
  skeletonizer: ^2.1.1
  animated_flip_counter: ^0.3.4
  animations: ^2.1.1
  loading_animation_widget: ^1.3.0
  modal_bottom_sheet: ^3.0.0
  text_scroll: ^0.2.1
  figma_squircle: ^0.6.3
  dynamic_color: ^1.8.1

  # Media
  innertube_dart:
    path: "../innertube_dart"
    # git: "https://github.com/6Rix6/innertube_dart.git"
  audio_service: ^0.18.18
  just_audio: ^0.10.5

  # System
  get: ^4.7.3
  webview_flutter: ^4.13.0
  flutter_inappwebview: ^6.1.5
  shared_preferences: ^2.5.4
  http: ^1.6.0
  permission_handler: ^12.0.1
  nampack:
    git:
      url: https://github.com/MSOB7YY/nampack

  # i18n
  slang: ^4.11.1
  slang_flutter: ^4.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
